inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-capybara

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
  DisplayCopNames: true

Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment: 
  Enabled: false
Gemspec/RequireMFA: 
  Enabled: false
Layout/LineContinuationLeadingSpace: 
  Enabled: false
Layout/LineContinuationSpacing: 
  Enabled: false
Layout/LineEndStringConcatenationIndentation: 
  Enabled: false
Layout/SpaceBeforeBrackets: 
  Enabled: false
Lint/AmbiguousAssignment: 
  Enabled: false
Lint/AmbiguousOperatorPrecedence: 
  Enabled: false
Lint/AmbiguousRange: 
  Enabled: false
Lint/ConstantOverwrittenInRescue: 
  Enabled: false
Lint/DeprecatedConstants: 
  Enabled: false
Lint/DuplicateBranch: 
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement: 
  Enabled: false
Lint/EmptyBlock: 
  Enabled: false
Lint/EmptyClass: 
  Enabled: false
Lint/EmptyInPattern: 
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler: 
  Enabled: false
Lint/LambdaWithoutLiteralBlock: 
  Enabled: false
Lint/NoReturnInBeginEndBlocks: 
  Enabled: false
Lint/NonAtomicFileOperation: 
  Enabled: false
Lint/NumberedParameterAssignment: 
  Enabled: false
Lint/OrAssignmentToConstant: 
  Enabled: false
Lint/RedundantDirGlobSort: 
  Enabled: false
Lint/RefinementImportMethods: 
  Enabled: false
Lint/RequireRelativeSelfPath: 
  Enabled: false
Lint/SymbolConversion: 
  Enabled: false
Lint/ToEnumArguments: 
  Enabled: false
Lint/TripleQuotes: 
  Enabled: false
Lint/UnexpectedBlockArity: 
  Enabled: false
Lint/UnmodifiedReduceAccumulator: 
  Enabled: false
Lint/UselessRuby2Keywords: 
  Enabled: false
Naming/BlockForwarding: 
  Enabled: false
Security/CompoundHash: 
  Enabled: false
Security/IoMethods: 
  Enabled: false
Style/ArgumentsForwarding: 
  Enabled: false
Style/CollectionCompact: 
  Enabled: false
Style/DocumentDynamicEvalDefinition: 
  Enabled: false
Style/EndlessMethod: 
  Enabled: false
Style/EnvHome: 
  Enabled: false
Style/FetchEnvVar: 
  Enabled: false
Style/FileRead: 
  Enabled: false
Style/FileWrite: 
  Enabled: false
Style/HashConversion: 
  Enabled: false
Style/HashExcept: 
  Enabled: false
Style/IfWithBooleanLiteralBranches: 
  Enabled: false
Style/InPatternThen: 
  Enabled: false
Style/MapCompactWithConditionalBlock: 
  Enabled: false
Style/MapToHash: 
  Enabled: false
Style/MultilineInPatternThen:
  Enabled: false
Style/NegatedIfElseCondition: 
  Enabled: false
Style/NestedFileDirname: 
  Enabled: false
Style/NilLambda: 
  Enabled: false
Style/NumberedParameters: 
  Enabled: false
Style/NumberedParametersLimit: 
  Enabled: false
Style/ObjectThen: 
  Enabled: false
Style/OpenStructUse: 
  Enabled: false
Style/QuotedSymbols: 
  Enabled: false
Style/RedundantArgument: 
  Enabled: false
Style/RedundantInitialize: 
  Enabled: false
Style/RedundantSelfAssignmentBranch: 
  Enabled: false
Style/SelectByRegexp: 
  Enabled: false
Style/StringChars: 
  Enabled: false
Style/SwapValues: 
  Enabled: false